-- ============================================================
-- EventHub - Complete Database Schema
-- Run this entire script in your Supabase SQL Editor
-- ============================================================

-- 1. Admin credentials table
CREATE TABLE IF NOT EXISTS admin_username_pass (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    college_name TEXT,
    college_code VARCHAR(50) NOT NULL UNIQUE
);

-- 2. Events table
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    category VARCHAR(100) NOT NULL,
    organizer VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    description TEXT,
    image_path VARCHAR(255),
    registration_link VARCHAR(500),
    sheet_link VARCHAR(500),
    admin_id BIGINT NOT NULL REFERENCES admin_username_pass(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Event registrations (students) table
CREATE TABLE IF NOT EXISTS event_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    student_name VARCHAR(255) NOT NULL,
    student_email VARCHAR(255) NOT NULL,
    attended BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Subscribers table (email notifications)
CREATE TABLE IF NOT EXISTS subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    admin_id BIGINT NOT NULL REFERENCES admin_username_pass(id) ON DELETE CASCADE,
    subscribed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'unsubscribed')),
    CONSTRAINT unique_email_per_admin UNIQUE (email, admin_id)
);

-- ============================================================
-- Row Level Security (RLS) Policies
-- Required for Supabase access via the anon/publishable key
-- ============================================================

ALTER TABLE public.admin_username_pass ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Allow public access to admin_username_pass" ON public.admin_username_pass;
DROP POLICY IF EXISTS "Allow public access to events" ON public.events;
DROP POLICY IF EXISTS "Allow public access to event_registrations" ON public.event_registrations;
DROP POLICY IF EXISTS "Allow public access to subscribers" ON public.subscribers;

-- Create policies allowing anon role full access
-- (Flask backend uses the anon/publishable key)
CREATE POLICY "Allow public access to admin_username_pass"
ON public.admin_username_pass FOR ALL TO anon
USING (true) WITH CHECK (true);

CREATE POLICY "Allow public access to events"
ON public.events FOR ALL TO anon
USING (true) WITH CHECK (true);

CREATE POLICY "Allow public access to event_registrations"
ON public.event_registrations FOR ALL TO anon
USING (true) WITH CHECK (true);

CREATE POLICY "Allow public access to subscribers"
ON public.subscribers FOR ALL TO anon
USING (true) WITH CHECK (true);
