-- ============================================
-- Supabase Migration Schema for EventHub
-- Run this entire script in the Supabase SQL Editor
-- ============================================

-- 1. Admin credentials table
CREATE TABLE admin_username_pass (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    -- Pre-hashed password for 'admin123' using werkzeug's default pbkdf2 method
    password VARCHAR(255) NOT NULL DEFAULT 'scrypt:32768:8:1$y6XmYyGjQJpT8uK4$b2b9185a7e114dbb7d287018318db50f555d4960eb5a538563eb6b95b452817d23a7bb7d5d1eaebbb0f719b02b5e28a6f3b0e1180292723c3b0eb10b91d34f0d'
);

-- Insert the default admin user
INSERT INTO admin_username_pass (username)
VALUES ('admin')
ON CONFLICT (username) DO NOTHING;

-- 2. Events table
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    category VARCHAR(100) NOT NULL,
    organizer VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    description TEXT,
    image_path VARCHAR(255),
    registration_link VARCHAR(500),
    sheet_link VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Event registrations (students) table
CREATE TABLE event_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    student_name VARCHAR(255) NOT NULL,
    student_email VARCHAR(255) NOT NULL,
    attended BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Subscribers table (email notifications)
CREATE TABLE subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    subscribed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'unsubscribed'))
);
